version: "3.5"
services:
  psql:
    container_name: sign_bot_psql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_EXTENSIONS: hstore
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
networks:
  temporal-network:
    driver: bridge
    name: temporal-network